//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishimotto.Console {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class IshimottoSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static IshimottoSettings defaultInstance = ((IshimottoSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new IshimottoSettings())));
        
        public static IshimottoSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Nugets")]
        public string DownloadDirectory {
            get {
                return ((string)(this["DownloadDirectory"]));
            }
            set {
                this["DownloadDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteTempFile {
            get {
                return ((bool)(this["DeleteTempFile"]));
            }
            set {
                this["DeleteTempFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Nugets\\AriaLog")]
        public string AriaLogPath {
            get {
                return ((string)(this["AriaLogPath"]));
            }
            set {
                this["AriaLogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ERROR")]
        public string AriaLogLevel {
            get {
                return ((string)(this["AriaLogLevel"]));
            }
            set {
                this["AriaLogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public uint MaxConnections {
            get {
                return ((uint)(this["MaxConnections"]));
            }
            set {
                this["MaxConnections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Logger.Config\"")]
        public string LoggerFileName {
            get {
                return ((string)(this["LoggerFileName"]));
            }
            set {
                this["LoggerFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.nuget.org/api/v2/")]
        public string NuGetUrl {
            get {
                return ((string)(this["NuGetUrl"]));
            }
            set {
                this["NuGetUrl"] = value;
            }
        }
    }
}
